
import React, { useRef, useState, useEffect } from 'react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { X, Share2, Printer, Loader2, Download, Globe, ChevronLeft, MapPin, Phone, Mail, FileText } from 'lucide-react';
import type { Order, Client, Store, CompanyInfo } from '../types';
import { OrderStatus } from '../types';
import Logo from './Logo';

// --- Constants ---
const A4_WIDTH_PX = 794;  // Standard A4 width at 96 DPI
const A4_HEIGHT_PX = 1123; // Standard A4 height at 96 DPI

// --- Types ---
type LangCode = 'ar' | 'en' | 'fr';
type InvoiceAction = 'share' | 'print' | 'download';

interface InvoiceModalProps {
    isOpen: boolean;
    onClose: () => void;
    order: Order;
    client: Client;
    store: Store;
    companyInfo: CompanyInfo;
}

// --- Helper: Invoice Template Component (Pure UI) ---
const InvoiceTemplate: React.FC<{
    order: Order;
    client: Client;
    store: Store;
    companyInfo: CompanyInfo;
    lang: LangCode;
}> = ({ order, client, store, companyInfo, lang }) => {
    
    // Logic
    const isShippingPending = [OrderStatus.NEW, OrderStatus.ORDERED, OrderStatus.SHIPPED_FROM_STORE].includes(order.status);
    const productPrice = Number(order.priceInMRU) || 0;
    const commission = Number(order.commission) || 0;
    const shipping = isShippingPending ? 0 : (Number(order.shippingCost) || 0);
    const delivery = isShippingPending ? 0 : (Number(order.localDeliveryCost) || 0);
    const subTotal = productPrice + commission; 
    const totalDue = subTotal + shipping + delivery;
    const paid = Number(order.amountPaid) || 0;
    const remaining = totalDue - paid;
    const isPaid = remaining <= 0 && totalDue > 0;

    // Translations
    const t = {
        ar: {
            title: 'فاتورة ضريبية', proforma: 'فاتورة مبدئية', billTo: 'بيانات العميل', invoiceDetails: 'تفاصيل الفاتورة',
            store: 'المتجر', description: 'البيان / الوصف', price: 'السعر', commission: 'العمولة',
            shipping: 'الشحن الدولي', delivery: 'التوصيل المحلي', total: 'الإجمالي الكلي', paid: 'المدفوع',
            remaining: 'المتبقي للدفع', method: 'طريقة الدفع', status: 'حالة الدفع', paidStatus: 'خالص',
            unpaidStatus: 'متبقي', shippingNote: 'ملاحظة: تكلفة الشحن (والوزن النهائي) تحتسب وتدفع عند وصول الطلب إلى المكتب.',
            terms: 'شكراً لثقتكم بنا. يرجى الاحتفاظ برقم الفاتورة للمراجعة.', termsHeader: 'الشروط والأحكام',
            currency: 'أوقية', qty: 'العدد', amount: 'المجموع', productVal: 'قيمة المنتجات', fees: 'رسوم الخدمة',
            generated: 'تم التوليد بواسطة', date: 'التاريخ'
        },
        en: {
            title: 'TAX INVOICE', proforma: 'PROFORMA INVOICE', billTo: 'Bill To', invoiceDetails: 'Invoice Details',
            store: 'Store', description: 'Description', price: 'Price', commission: 'Commission',
            shipping: 'Intl. Shipping', delivery: 'Local Delivery', total: 'Grand Total', paid: 'Amount Paid',
            remaining: 'Balance Due', method: 'Payment Method', status: 'Payment Status', paidStatus: 'PAID',
            unpaidStatus: 'UNPAID', shippingNote: 'Note: Shipping fees are calculated upon arrival.',
            terms: 'Thank you for your business.', termsHeader: 'Terms & Conditions',
            currency: 'MRU', qty: 'Qty', amount: 'Amount', productVal: 'Product Value', fees: 'Service Fees',
            generated: 'Generated by', date: 'Date'
        },
        fr: {
            title: 'FACTURE', proforma: 'FACTURE PROFORMA', billTo: 'Facturer à', invoiceDetails: 'Détails',
            store: 'Magasin', description: 'Description', price: 'Prix', commission: 'Commission',
            shipping: 'Transport Intl.', delivery: 'Livraison', total: 'Total Général', paid: 'Payé',
            remaining: 'Reste à payer', method: 'Mode paiement', status: 'État', paidStatus: 'PAYÉ',
            unpaidStatus: 'IMPAYÉ', shippingNote: 'Note : Les frais de port sont calculés à l\'arrivée.',
            terms: 'Merci de votre confiance.', termsHeader: 'Termes et conditions',
            currency: 'MRU', qty: 'Qté', amount: 'Montant', productVal: 'Valeur Produit', fees: 'Frais',
            generated: 'Généré par', date: 'Date'
        }
    };

    const txt = t[lang];
    const isRtl = lang === 'ar';
    const font = isRtl ? 'Cairo, sans-serif' : 'Arial, sans-serif';
    const invoiceTitle = isShippingPending ? txt.proforma : txt.title;

    // CRITICAL: Robust CSS for Arabic text rendering
    const containerStyle: React.CSSProperties = { 
        fontFamily: font, 
        direction: isRtl ? 'rtl' : 'ltr',
        letterSpacing: '0px', // Crucial for Arabic letters connection
        fontVariantLigatures: 'none', // Helps preventing weird reshaping
        textRendering: 'geometricPrecision',
        WebkitFontSmoothing: 'antialiased',
        width: '100%',
        height: '100%',
        backgroundColor: 'white',
        color: '#000', // Pure black for better contrast
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
    };

    // Style for table headers
    const thStyle: React.CSSProperties = {
        padding: '12px 16px',
        textAlign: isRtl ? 'right' : 'left',
        backgroundColor: '#f1f5f9',
        borderBottom: '2px solid #e2e8f0',
        fontWeight: 'bold',
        color: '#1e293b',
        fontSize: '14px'
    };

    // Style for table cells
    const tdStyle: React.CSSProperties = {
        padding: '16px',
        borderBottom: '1px solid #f1f5f9',
        color: '#000000', // Explicit black
        fontWeight: '600',
        fontSize: '15px'
    };

    return (
        <div style={containerStyle} dir={isRtl ? 'rtl' : 'ltr'} id="invoice-content">
            {/* Header */}
            <div style={{ backgroundColor: '#0f172a', color: 'white', padding: '40px', paddingBottom: '48px', position: 'relative' }}>
                <div style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                        <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: '16px' }}>
                            <div style={{ width: '64px', height: '64px', backgroundColor: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '12px', padding: '4px' }}>
                                {companyInfo.logo ? <img src={companyInfo.logo} style={{width:'100%', height:'100%', objectFit:'contain'}} alt="logo"/> : <Logo className="w-12 h-12"/>}
                            </div>
                            <div>
                                <h1 style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, letterSpacing: '0px' }}>{companyInfo.name}</h1>
                                <p style={{ fontSize: '10px', opacity: 0.8, textTransform: 'uppercase', letterSpacing: isRtl ? '0px' : '1px', marginTop: '4px' }}>{txt.generated} Fast Comand</p>
                            </div>
                        </div>
                        <div style={{ fontSize: '13px', opacity: 0.9, marginTop: '8px', fontWeight: '500', lineHeight: '1.5' }}>
                            {companyInfo.phone && <p style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '8px' }}><Phone size={12} strokeWidth={3}/> <span dir="ltr">{companyInfo.phone}</span></p>}
                            {companyInfo.email && <p style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '8px' }}><Mail size={12} strokeWidth={3}/> {companyInfo.email}</p>}
                            {companyInfo.address && <p style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '8px' }}><MapPin size={12} strokeWidth={3}/> {companyInfo.address}</p>}
                        </div>
                    </div>
                    
                    <div style={{ textAlign: isRtl ? 'left' : 'right' }}>
                        <h2 style={{ fontSize: '28px', fontWeight: '900', margin: 0, letterSpacing: '0px' }}>{invoiceTitle}</h2>
                        <p style={{ color: '#818cf8', fontFamily: 'monospace', fontWeight: 'bold', fontSize: '18px', marginTop: '8px' }}>#{order.localOrderId}</p>
                        <div style={{ marginTop: '16px', backgroundColor: 'rgba(255,255,255,0.1)', padding: '6px 16px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)', display: 'inline-block' }}>
                            <p style={{ fontSize: '10px', opacity: 0.8, margin: 0, textTransform: 'uppercase' }}>{txt.date}</p>
                            <p style={{ fontSize: '14px', fontWeight: 'bold', fontFamily: 'monospace', margin: 0 }}>{new Date().toLocaleDateString('en-GB')}</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Bill To & Details */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px', paddingLeft: '40px', paddingRight: '40px', marginTop: '-32px', position: 'relative', zIndex: 10 }}>
                <div style={{ backgroundColor: 'white', padding: '24px', borderRadius: '12px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}>
                    <h3 style={{ fontSize: '12px', fontWeight: 'bold', color: '#94a3b8', textTransform: 'uppercase', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px', letterSpacing: isRtl ? '0px' : '1px' }}>{txt.billTo}</h3>
                    <div style={{ color: '#1e293b' }}>
                        <p style={{ fontSize: '20px', fontWeight: 'bold', margin: '0 0 4px 0' }}>{client.name}</p>
                        <p style={{ fontSize: '16px', fontFamily: 'monospace', color: '#475569', margin: 0, textAlign: isRtl ? 'right' : 'left' }} dir="ltr">{client.phone}</p>
                        {client.address && <p style={{ fontSize: '14px', color: '#64748b', margin: '4px 0 0 0' }}>{client.address}</p>}
                    </div>
                </div>
                <div style={{ backgroundColor: 'white', padding: '24px', borderRadius: '12px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}>
                    <h3 style={{ fontSize: '12px', fontWeight: 'bold', color: '#94a3b8', textTransform: 'uppercase', marginBottom: '16px', letterSpacing: isRtl ? '0px' : '1px' }}>{txt.invoiceDetails}</h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '14px' }}>
                            <span style={{ color: '#64748b', fontWeight: '500' }}>{txt.store}</span>
                            <span style={{ fontWeight: 'bold', color: '#1e293b' }}>{store.name}</span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '14px' }}>
                            <span style={{ color: '#64748b', fontWeight: '500' }}>{txt.status}</span>
                            <span style={{ fontWeight: 'bold', padding: '2px 8px', borderRadius: '4px', fontSize: '12px', backgroundColor: isPaid ? '#dcfce7' : '#fee2e2', color: isPaid ? '#15803d' : '#b91c1c' }}>
                                {isPaid ? txt.paidStatus : txt.unpaidStatus}
                            </span>
                        </div>
                        {order.globalOrderId && (
                            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '14px' }}>
                                <span style={{ color: '#64748b', fontWeight: '500' }}>Ref ID</span>
                                <span style={{ fontFamily: 'monospace', color: '#334155' }}>{order.globalOrderId}</span>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Table */}
            <div style={{ padding: '40px', paddingTop: '32px', flexGrow: 1 }}>
                <div style={{ border: '1px solid #e2e8f0', borderRadius: '12px', overflow: 'hidden' }}>
                    <table style={{ width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' }}>
                        <thead>
                            <tr>
                                <th style={{ ...thStyle, width: '50%' }}>{txt.description}</th>
                                <th style={{ ...thStyle, width: '20%', textAlign: 'center' }}>{txt.qty}</th>
                                <th style={{ ...thStyle, width: '30%', textAlign: isRtl ? 'left' : 'right' }}>{txt.amount}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style={tdStyle}>
                                    <p style={{ margin: 0, fontWeight: 'bold' }}>{txt.productVal}</p>
                                    {order.trackingNumber && <p style={{ margin: '4px 0 0 0', fontSize: '12px', color: '#64748b', fontFamily: 'monospace' }}>Track: {order.trackingNumber}</p>}
                                </td>
                                <td style={{ ...tdStyle, textAlign: 'center' }}>{order.quantity}</td>
                                <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right' }}>{productPrice.toLocaleString()}</td>
                            </tr>
                            <tr style={{ backgroundColor: '#f8fafc' }}>
                                <td style={tdStyle}>
                                    <span>{txt.commission}</span> <span style={{ fontSize: '12px', color: '#64748b', fontWeight: 'normal' }}>({txt.fees})</span>
                                </td>
                                <td style={{ ...tdStyle, textAlign: 'center' }}>-</td>
                                <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right' }}>{commission.toLocaleString()}</td>
                            </tr>
                            {!isShippingPending && (
                                <tr>
                                    <td style={tdStyle}>
                                        <p style={{ margin: 0, fontWeight: 'bold' }}>{txt.shipping}</p>
                                        <p style={{ margin: '4px 0 0 0', fontSize: '12px', color: '#64748b' }}>{order.weight} KG x Rate</p>
                                    </td>
                                    <td style={{ ...tdStyle, textAlign: 'center' }}>1</td>
                                    <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right' }}>{shipping.toLocaleString()}</td>
                                </tr>
                            )}
                            {!isShippingPending && delivery > 0 && (
                                <tr style={{ backgroundColor: '#f8fafc' }}>
                                    <td style={tdStyle}>{txt.delivery}</td>
                                    <td style={{ ...tdStyle, textAlign: 'center' }}>1</td>
                                    <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right' }}>{delivery.toLocaleString()}</td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>

                {isShippingPending && (
                    <div style={{ marginTop: '24px', padding: '16px', backgroundColor: '#fffbeb', border: '1px solid #fef3c7', borderRadius: '8px', display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
                        <div style={{ backgroundColor: '#fef3c7', padding: '6px', borderRadius: '50%', color: '#d97706' }}>
                            <Loader2 size={16} className="animate-spin-slow"/>
                        </div>
                        <p style={{ margin: 0, fontSize: '14px', color: '#92400e', fontWeight: 'bold', lineHeight: '1.5' }}>
                            {txt.shippingNote}
                        </p>
                    </div>
                )}
            </div>

            {/* Footer */}
            <div style={{ backgroundColor: '#f8fafc', padding: '40px', marginTop: 'auto', borderTop: '1px solid #e2e8f0' }}>
                <div style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: '40px' }}>
                    <div style={{ width: '45%' }}>
                        <h4 style={{ fontSize: '14px', fontWeight: 'bold', color: '#334155', textTransform: 'uppercase', marginBottom: '12px', letterSpacing: isRtl ? '0px' : '1px' }}>{txt.method}</h4>
                        <span style={{ padding: '8px 16px', backgroundColor: 'white', border: '1px solid #cbd5e1', borderRadius: '8px', display: 'inline-block', fontWeight: 'bold', color: '#1e293b', boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)' }}>{order.paymentMethod || 'Cash'}</span>
                        <div style={{ marginTop: '20px', fontSize: '14px', color: '#475569', lineHeight: '1.6' }}>
                            <p style={{ margin: 0, fontWeight: 'bold' }}>{companyInfo.name}</p>
                            <p style={{ margin: 0, textAlign: isRtl ? 'right' : 'left' }} dir="ltr">{companyInfo.phone}</p>
                            <p style={{ margin: 0 }}>{companyInfo.address}</p>
                        </div>
                    </div>

                    <div style={{ width: '40%' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px', color: '#334155', fontSize: '16px' }}>
                            <span style={{ fontWeight: 'bold' }}>{txt.total}</span>
                            <span style={{ fontWeight: 'bold', fontFamily: 'monospace', fontSize: '20px' }}>{totalDue.toLocaleString()} <span style={{ fontSize: '12px' }}>{txt.currency}</span></span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '12px', color: '#15803d', borderBottom: '1px solid #e2e8f0', paddingBottom: '12px' }}>
                            <span style={{ fontWeight: 'bold' }}>{txt.paid}</span>
                            <span style={{ fontWeight: 'bold', fontFamily: 'monospace', fontSize: '18px' }}>{paid.toLocaleString()}</span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '16px', borderRadius: '12px', backgroundColor: remaining > 0 ? '#1e293b' : '#15803d', color: 'white', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}>
                            <span style={{ fontWeight: 'bold', textTransform: 'uppercase', fontSize: '14px', letterSpacing: isRtl ? '0px' : '1px' }}>{txt.remaining}</span>
                            <span style={{ fontWeight: '900', fontFamily: 'monospace', fontSize: '24px' }}>{remaining.toLocaleString()} <span style={{ fontSize: '12px', opacity: 0.7 }}>{txt.currency}</span></span>
                        </div>
                    </div>
                </div>

                <div style={{ marginTop: '40px', paddingTop: '32px', borderTop: '1px solid #e2e8f0', textAlign: 'center' }}>
                    <h5 style={{ fontSize: '10px', fontWeight: 'bold', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: isRtl ? '0px' : '1px', marginBottom: '12px' }}>{txt.termsHeader}</h5>
                    <p style={{ fontSize: '12px', color: '#64748b', lineHeight: '1.6', whiteSpace: 'pre-wrap', margin: 0, paddingLeft: '32px', paddingRight: '32px' }}>
                        {companyInfo.invoiceTerms || txt.terms}
                    </p>
                </div>
            </div>
            
            <div style={{ height: '8px', width: '100%', background: 'linear-gradient(to right, #4f46e5, #f59e0b)' }}></div>
        </div>
    );
};

// --- Main Modal Component ---
const InvoiceModal: React.FC<InvoiceModalProps> = ({ isOpen, onClose, order, client, store, companyInfo }) => {
    const hiddenInvoiceRef = useRef<HTMLDivElement>(null); 
    const [isGenerating, setIsGenerating] = useState(false);
    const [selectedLang, setSelectedLang] = useState<LangCode | null>(null);
    const [previewScale, setPreviewScale] = useState(1);

    useEffect(() => {
        if (isOpen) setSelectedLang(null);
    }, [isOpen]);

    useEffect(() => {
        const handleResize = () => {
            const padding = 32;
            const availableWidth = window.innerWidth - padding;
            const scale = Math.min(availableWidth / A4_WIDTH_PX, 1); 
            setPreviewScale(scale);
        };
        
        if (isOpen) {
            handleResize();
            window.addEventListener('resize', handleResize);
        }
        return () => window.removeEventListener('resize', handleResize);
    }, [isOpen]);

    if (!isOpen) return null;

    const generateAndShare = async (action: InvoiceAction) => {
        if (!hiddenInvoiceRef.current) return;
        setIsGenerating(true);

        try {
            await document.fonts.ready;
            // Slightly longer delay to ensure layout stability
            await new Promise(resolve => setTimeout(resolve, 800));

            const canvas = await html2canvas(hiddenInvoiceRef.current, {
                scale: 2, // High quality
                useCORS: true,
                allowTaint: true,
                backgroundColor: '#ffffff',
                width: A4_WIDTH_PX,
                height: A4_HEIGHT_PX,
                windowWidth: 1200, // Force Desktop Layout
                logging: false,
                onclone: (clonedDoc) => {
                    const el = clonedDoc.getElementById('hidden-invoice-container');
                    if (el) {
                        el.style.display = 'block';
                        el.style.visibility = 'visible';
                        el.style.position = 'relative';
                    }
                }
            });

            if (action === 'print') {
                const imgData = canvas.toDataURL('image/png');
                const printWindow = window.open('', '_blank');
                if (printWindow) {
                    printWindow.document.write(`
                        <html>
                            <head><title>Invoice #${order.localOrderId}</title></head>
                            <body style="margin:0; display:flex; justify-content:center; background:#eee;">
                                <img src="${imgData}" style="width:100%; max-width:210mm; background:white;" onload="window.print();"/>
                            </body>
                        </html>
                    `);
                    printWindow.document.close();
                }
            } else {
                const imgData = canvas.toDataURL('image/jpeg', 0.85);
                const pdf = new jsPDF('p', 'mm', 'a4');
                const pdfWidth = pdf.internal.pageSize.getWidth();
                const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

                pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight);
                const pdfBlob = pdf.output('blob');
                const fileName = `Invoice-${order.localOrderId}.pdf`;
                const file = new File([pdfBlob], fileName, { type: 'application/pdf' });

                if (action === 'share') {
                    if (navigator.canShare && navigator.canShare({ files: [file] })) {
                        try {
                            await navigator.share({
                                files: [file],
                                title: `Invoice ${order.localOrderId}`,
                                text: `الفاتورة الخاصة بالطلب #${order.localOrderId}`,
                            });
                        } catch (shareErr: any) {
                            if (shareErr.name !== 'AbortError') throw shareErr;
                        }
                    } else {
                        const url = URL.createObjectURL(pdfBlob);
                        const link = document.createElement('a');
                        link.href = url;
                        link.download = fileName;
                        document.body.appendChild(link);
                        link.click();
                        document.body.removeChild(link);
                        URL.revokeObjectURL(url);
                        alert('تم تحميل الفاتورة بنجاح.');
                    }
                } else if (action === 'download') {
                    const url = URL.createObjectURL(pdfBlob);
                    const link = document.createElement('a');
                    link.href = url;
                    link.download = fileName;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                    URL.revokeObjectURL(url);
                }
            }

        } catch (error) {
            console.error('Invoice generation error:', error);
            alert('حدث خطأ أثناء معالجة الفاتورة.');
        } finally {
            setIsGenerating(false);
        }
    };

    if (!selectedLang) {
        return (
            <div className="fixed inset-0 bg-slate-900/90 z-[120] flex flex-col items-center justify-center p-4 backdrop-blur-md" onClick={onClose}>
                <div className="bg-white dark:bg-gray-800 rounded-3xl shadow-2xl p-8 w-full max-w-sm text-center animate-in zoom-in-95 duration-200" onClick={e => e.stopPropagation()}>
                    <div className="w-20 h-20 bg-blue-50 dark:bg-blue-900/20 rounded-full flex items-center justify-center mx-auto mb-6 text-primary">
                        <Globe size={40} strokeWidth={1.5}/>
                    </div>
                    <h3 className="text-2xl font-black text-gray-800 dark:text-white mb-2">لغة الفاتورة</h3>
                    <p className="text-gray-500 dark:text-gray-400 mb-8 text-sm leading-relaxed">اختر اللغة المناسبة لعرض ومشاركة الفاتورة مع العميل</p>
                    
                    <div className="space-y-3">
                        <button onClick={() => setSelectedLang('ar')} className="w-full p-4 rounded-2xl border-2 border-gray-100 dark:border-gray-700 hover:border-primary hover:bg-blue-50 dark:hover:bg-blue-900/20 flex items-center justify-between group transition-all">
                            <span className="font-bold text-gray-700 dark:text-gray-200 text-lg">العربية</span>
                            <span className="text-2xl grayscale group-hover:grayscale-0 transition-all">🇦🇪</span>
                        </button>
                        <button onClick={() => setSelectedLang('en')} className="w-full p-4 rounded-2xl border-2 border-gray-100 dark:border-gray-700 hover:border-primary hover:bg-blue-50 dark:hover:bg-blue-900/20 flex items-center justify-between group transition-all">
                            <span className="font-bold text-gray-700 dark:text-gray-200 text-lg">English</span>
                            <span className="text-2xl grayscale group-hover:grayscale-0 transition-all">🇺🇸</span>
                        </button>
                        <button onClick={() => setSelectedLang('fr')} className="w-full p-4 rounded-2xl border-2 border-gray-100 dark:border-gray-700 hover:border-primary hover:bg-blue-50 dark:hover:bg-blue-900/20 flex items-center justify-between group transition-all">
                            <span className="font-bold text-gray-700 dark:text-gray-200 text-lg">Français</span>
                            <span className="text-2xl grayscale group-hover:grayscale-0 transition-all">🇫🇷</span>
                        </button>
                    </div>
                    <button onClick={onClose} className="mt-8 text-gray-400 hover:text-gray-600 text-sm font-bold">إلغاء</button>
                </div>
            </div>
        );
    }

    return (
        <>
            {isGenerating && (
                <div className="fixed inset-0 z-[10000] bg-white/90 backdrop-blur-md flex flex-col items-center justify-center p-6 text-center">
                    <div className="relative w-24 h-24 mb-6">
                        <div className="absolute inset-0 border-4 border-primary/20 rounded-full"></div>
                        <div className="absolute inset-0 border-4 border-primary rounded-full border-t-transparent animate-spin"></div>
                        <div className="absolute inset-0 flex items-center justify-center text-primary">
                            <FileText size={32}/>
                        </div>
                    </div>
                    <h3 className="text-xl font-bold text-slate-800 mb-2">جاري توليد الفاتورة</h3>
                    <p className="text-slate-500 max-w-xs mx-auto">نقوم الآن بتحويل الفاتورة إلى ملف PDF عالي الجودة، يرجى الانتظار قليلاً...</p>
                </div>
            )}

            <div className="fixed inset-0 bg-slate-900/95 z-[120] flex flex-col p-0 backdrop-blur-sm overflow-hidden">
                <div className="absolute top-0 left-0 w-full p-4 flex justify-between items-center z-50 pointer-events-none">
                    <button onClick={() => setSelectedLang(null)} className="p-3 bg-slate-800/80 hover:bg-slate-700 text-white rounded-full backdrop-blur-md pointer-events-auto transition-all flex items-center gap-2 px-5 shadow-lg border border-white/10">
                        <ChevronLeft size={20}/> <span className="text-sm font-bold hidden sm:inline">السابق</span>
                    </button>
                    <button onClick={onClose} className="p-3 bg-slate-800/80 hover:bg-slate-700 text-white rounded-full backdrop-blur-md pointer-events-auto transition-all shadow-lg border border-white/10">
                        <X size={24}/>
                    </button>
                </div>

                <div className="flex-1 overflow-y-auto w-full custom-scrollbar flex justify-center">
                    <div className="pt-24 pb-32 px-4" style={{ width: '100%', display: 'flex', justifyContent: 'center' }}>
                        <div style={{
                            width: `${A4_WIDTH_PX}px`,
                            height: `${A4_HEIGHT_PX}px`,
                            transform: `scale(${previewScale})`,
                            transformOrigin: 'top center',
                            marginBottom: `${-(A4_HEIGHT_PX * (1 - previewScale))}px`,
                            boxShadow: '0 20px 50px rgba(0,0,0,0.5)'
                        }}>
                            <InvoiceTemplate order={order} client={client} store={store} companyInfo={companyInfo} lang={selectedLang} />
                        </div>
                    </div>
                </div>

                {/* This is the hidden container captured by html2canvas */}
                <div 
                    id="hidden-invoice-container"
                    ref={hiddenInvoiceRef}
                    style={{
                        position: 'fixed',
                        top: 0,
                        left: 0,
                        width: `${A4_WIDTH_PX}px`,
                        height: `${A4_HEIGHT_PX}px`,
                        zIndex: -100, 
                        visibility: 'hidden', 
                        backgroundColor: 'white',
                        pointerEvents: 'none'
                    }}
                >
                    <InvoiceTemplate order={order} client={client} store={store} companyInfo={companyInfo} lang={selectedLang} />
                </div>

                {/* Action Bar */}
                <div className="absolute bottom-6 left-1/2 transform -translate-x-1/2 bg-white/10 backdrop-blur-md border border-white/20 p-2 rounded-2xl flex gap-3 shadow-2xl z-50">
                    <button 
                        onClick={() => generateAndShare('share')}
                        disabled={isGenerating}
                        className="flex flex-col items-center justify-center w-16 h-16 rounded-xl bg-white hover:bg-gray-100 text-primary transition-all active:scale-95 group"
                    >
                        <Share2 size={24} className="group-hover:-translate-y-1 transition-transform"/>
                        <span className="text-[10px] font-bold mt-1">إرسال</span>
                    </button>

                    <button 
                        onClick={() => generateAndShare('print')}
                        disabled={isGenerating}
                        className="flex flex-col items-center justify-center w-16 h-16 rounded-xl bg-white hover:bg-gray-100 text-primary transition-all active:scale-95 group"
                    >
                        <Printer size={24} className="group-hover:-translate-y-1 transition-transform"/>
                        <span className="text-[10px] font-bold mt-1">طباعة</span>
                    </button>

                    <button 
                        onClick={() => generateAndShare('download')}
                        disabled={isGenerating}
                        className="flex flex-col items-center justify-center w-16 h-16 rounded-xl bg-primary text-white hover:bg-primary-dark transition-all active:scale-95 group shadow-lg shadow-primary/30"
                    >
                        <Download size={24} className="group-hover:-translate-y-1 transition-transform"/>
                        <span className="text-[10px] font-bold mt-1">حفظ</span>
                    </button>
                </div>
            </div>
        </>
    );
};

export default InvoiceModal;
