
import React, { useRef, useState, useEffect } from 'react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { X, Share2, Printer, Loader2, Download, Globe, ChevronLeft, MapPin, Phone, Mail, FileText, CheckCircle2, AlertCircle, Wallet, Check } from 'lucide-react';
import type { Order, Client, Store, CompanyInfo } from '../types';
import { OrderStatus } from '../types';
import Logo from './Logo';

// --- Constants ---
const A4_WIDTH_PX = 794;   // Standard A4 width at 96 DPI
const A4_HEIGHT_PX = 1123; // Standard A4 height at 96 DPI

// --- Types ---
type LangCode = 'ar' | 'en' | 'fr';
type InvoiceAction = 'share' | 'print' | 'download';
type GenerationStatus = 'idle' | 'generating' | 'ready_to_share' | 'error';

interface InvoiceModalProps {
    isOpen: boolean;
    onClose: () => void;
    order: Order;
    client: Client;
    store: Store;
    companyInfo: CompanyInfo;
    onSuccess?: () => void;
}

// --- Helper: Invoice Template Component (Pure UI) ---
const InvoiceTemplate: React.FC<{
    order: Order;
    client: Client;
    store: Store;
    companyInfo: CompanyInfo;
    lang: LangCode;
}> = ({ order, client, store, companyInfo, lang }) => {
    
    // Logic - Ensure numbers are valid
    const isShippingPending = [OrderStatus.NEW, OrderStatus.ORDERED, OrderStatus.SHIPPED_FROM_STORE].includes(order.status);
    const originalPrice = Number(order.price) || 0;
    const productPriceMRU = Number(order.priceInMRU) || 0;
    const commission = Number(order.commission) || 0;
    const shipping = isShippingPending ? 0 : (Number(order.shippingCost) || 0);
    const delivery = isShippingPending ? 0 : (Number(order.localDeliveryCost) || 0);
    
    const subTotal = productPriceMRU + commission; 
    const totalDue = subTotal + shipping + delivery;
    const paid = Number(order.amountPaid) || 0;
    const remaining = totalDue - paid;
    const isPaid = remaining <= 0 && totalDue > 0;

    // Translations
    const t = {
        ar: {
            title: 'فاتورة', proforma: 'فاتورة', billTo: 'بيانات العميل', invoiceDetails: 'تفاصيل الفاتورة',
            store: 'المتجر', description: 'البيان', price: 'السعر', commission: 'العمولة',
            shipping: 'الشحن الدولي', delivery: 'التوصيل المحلي', total: 'الإجمالي الكلي', paid: 'المدفوع',
            remaining: 'المتبقي للدفع', method: 'طريقة الدفع', status: 'حالة الدفع', paidStatus: 'خالص',
            unpaidStatus: 'متبقي', shippingNote: 'ملاحظة: تكلفة الشحن (والوزن النهائي) تحتسب وتدفع عند وصول الطلب إلى المكتب.',
            terms: 'شكراً لثقتكم بنا. يرجى الاحتفاظ برقم الفاتورة للمراجعة.', termsHeader: 'الشروط والأحكام',
            currency: 'أوقية', qty: 'العدد', amount: 'المجموع (MRU)', productVal: 'قيمة المنتجات', fees: 'رسوم المكتب',
            generated: 'تم التوليد بواسطة', date: 'التاريخ', expected: 'توقع الوصول',
            originalPrice: 'السعر الأصلي', globalId: 'رقم الطلب العالمي'
        },
        en: {
            title: 'INVOICE', proforma: 'INVOICE', billTo: 'Bill To', invoiceDetails: 'Invoice Details',
            store: 'Store', description: 'Description', price: 'Price', commission: 'Commission',
            shipping: 'Intl. Shipping', delivery: 'Local Delivery', total: 'Grand Total', paid: 'Amount Paid',
            remaining: 'Balance Due', method: 'Payment Method', status: 'Payment Status', paidStatus: 'PAID',
            unpaidStatus: 'UNPAID', shippingNote: 'Note: Shipping fees are calculated upon arrival.',
            terms: 'Thank you for your business.', termsHeader: 'Terms & Conditions',
            currency: 'MRU', qty: 'Qty', amount: 'Amount (MRU)', productVal: 'Product Value', fees: 'Office Fees',
            generated: 'Generated by', date: 'Date', expected: 'Expected Arrival',
            originalPrice: 'Orig. Price', globalId: 'Global ID'
        },
        fr: {
            title: 'FACTURE', proforma: 'FACTURE', billTo: 'Facturer à', invoiceDetails: 'Détails',
            store: 'Magasin', description: 'Description', price: 'Prix', commission: 'Commission',
            shipping: 'Transport Intl.', delivery: 'Livraison', total: 'Total Général', paid: 'Payé',
            remaining: 'Reste à payer', method: 'Mode paiement', status: 'État', paidStatus: 'PAYÉ',
            unpaidStatus: 'IMPAYÉ', shippingNote: 'Note : Les frais de port sont calculés à l\'arrivée.',
            terms: 'Merci de votre confiance.', termsHeader: 'Termes et conditions',
            currency: 'MRU', qty: 'Qté', amount: 'Montant (MRU)', productVal: 'Valeur Produit', fees: 'Frais Bureau',
            generated: 'Généré par', date: 'Date', expected: 'Arrivée Prévue',
            originalPrice: 'Prix Orig.', globalId: 'ID Global'
        }
    };

    const txt = t[lang];
    const isRtl = lang === 'ar';
    const font = isRtl ? 'Cairo, sans-serif' : 'Arial, sans-serif';

    const containerStyle: React.CSSProperties = { 
        fontFamily: font, 
        direction: isRtl ? 'rtl' : 'ltr',
        width: `${A4_WIDTH_PX}px`,
        minHeight: `${A4_HEIGHT_PX}px`, 
        backgroundColor: '#ffffff',
        color: '#0f172a',
        display: 'flex',
        flexDirection: 'column',
        boxSizing: 'border-box',
        WebkitFontSmoothing: 'antialiased',
        lineHeight: 1.4
    };

    const thStyle: React.CSSProperties = {
        padding: '16px',
        textAlign: isRtl ? 'right' : 'left',
        backgroundColor: '#f1f5f9',
        borderBottom: '2px solid #cbd5e1',
        fontWeight: 'bold',
        color: '#334155',
        fontSize: '12px',
        textTransform: 'uppercase'
    };

    const tdStyle: React.CSSProperties = {
        padding: '16px',
        borderBottom: '1px solid #e2e8f0',
        verticalAlign: 'middle',
        fontSize: '14px',
        color: '#1e293b'
    };

    return (
        <div style={containerStyle} id="invoice-capture-target">
            {/* Header Branding */}
            <div style={{ backgroundColor: '#0f172a', color: 'white', padding: '50px 40px', position: 'relative' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                    <div style={{ display: 'flex', gap: '20px', alignItems: 'center' }}>
                        <div style={{ width: '80px', height: '80px', backgroundColor: 'white', borderRadius: '16px', padding: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                            {companyInfo.logo ? <img src={companyInfo.logo} style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} alt="logo" /> : <Logo className="w-14 h-14" />}
                        </div>
                        <div>
                            <h1 style={{ fontSize: '26px', fontWeight: '900', margin: 0 }}>{companyInfo.name}</h1>
                            <p style={{ margin: '4px 0 0', opacity: 0.7, fontSize: '12px' }}>Fast Comand SM</p>
                        </div>
                    </div>
                    <div style={{ textAlign: isRtl ? 'left' : 'right' }}>
                        <h2 style={{ fontSize: '32px', fontWeight: '900', margin: 0, color: '#818cf8' }}>{txt.title}</h2>
                        <div style={{ marginTop: '10px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                            <p style={{ margin: 0, fontSize: '16px', fontWeight: 'bold', fontFamily: 'monospace' }}>#{order.localOrderId}</p>
                            {/* Date in English numerals */}
                            <p style={{ margin: 0, fontSize: '13px', opacity: 0.8, fontFamily: 'monospace' }}>
                                {new Date(order.orderDate).toLocaleDateString('en-GB')}
                            </p>
                        </div>
                    </div>
                </div>
                
                <div style={{ display: 'flex', gap: '25px', marginTop: '30px', fontSize: '13px', opacity: 0.9 }}>
                    {companyInfo.phone && <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Phone size={14}/> <span dir="ltr">{companyInfo.phone}</span></div>}
                    {companyInfo.email && <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Mail size={14}/> {companyInfo.email}</div>}
                    {companyInfo.address && <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><MapPin size={14}/> {companyInfo.address}</div>}
                </div>
            </div>

            <div style={{ padding: '40px', paddingTop: '30px' }}>
                {/* Secondary Info Bar */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px', marginBottom: '40px' }}>
                    <div style={{ backgroundColor: '#f8fafc', padding: '20px', borderRadius: '16px', border: '1px solid #e2e8f0' }}>
                        <h3 style={{ fontSize: '11px', fontWeight: 'bold', color: '#64748b', textTransform: 'uppercase', marginBottom: '10px' }}>{txt.billTo}</h3>
                        <p style={{ fontSize: '20px', fontWeight: '900', margin: '0 0 4px', color: '#0f172a' }}>{client.name}</p>
                        <p style={{ fontSize: '16px', fontWeight: 'bold', fontFamily: 'monospace', color: '#475569', margin: 0 }} dir="ltr">{client.phone}</p>
                        {client.address && <p style={{ fontSize: '13px', color: '#64748b', marginTop: '6px' }}>{client.address}</p>}
                    </div>
                    <div>
                        <h3 style={{ fontSize: '11px', fontWeight: 'bold', color: '#64748b', textTransform: 'uppercase', marginBottom: '10px' }}>{txt.invoiceDetails}</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ fontSize: '13px', color: '#64748b' }}>{txt.store}</span><span style={{ fontSize: '13px', fontWeight: 'bold' }}>{store.name}</span></div>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ fontSize: '13px', color: '#64748b' }}>{txt.status}</span><span style={{ fontSize: '11px', fontWeight: '900', padding: '2px 10px', borderRadius: '20px', backgroundColor: isPaid ? '#ecfdf5' : '#fff1f2', color: isPaid ? '#059669' : '#e11d48' }}>{isPaid ? txt.paidStatus : txt.unpaidStatus}</span></div>
                            {order.expectedArrivalDate && <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ fontSize: '13px', color: '#64748b' }}>{txt.expected}</span><span style={{ fontSize: '13px', fontWeight: 'bold', fontFamily: 'monospace' }}>{new Date(order.expectedArrivalDate).toLocaleDateString('en-GB')}</span></div>}
                        </div>
                    </div>
                </div>

                {/* Main Table */}
                <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '30px' }}>
                    <thead>
                        <tr>
                            <th style={{ ...thStyle, width: '40%' }}>{txt.description}</th>
                            <th style={{ ...thStyle, textAlign: 'center', width: '10%' }}>{txt.qty}</th>
                            <th style={{ ...thStyle, textAlign: 'center', width: '25%' }}>{txt.originalPrice}</th>
                            <th style={{ ...thStyle, textAlign: isRtl ? 'left' : 'right', width: '25%' }}>{txt.amount}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style={tdStyle}>
                                <div style={{ fontWeight: '900', fontSize: '15px' }}>{txt.productVal}</div>
                                {order.globalOrderId && <div style={{ fontSize: '11px', color: '#64748b', marginTop: '4px', fontFamily: 'monospace' }}>{txt.globalId}: {order.globalOrderId}</div>}
                            </td>
                            <td style={{ ...tdStyle, textAlign: 'center', fontWeight: 'bold', fontFamily: 'monospace' }}>{order.quantity}</td>
                            <td style={{ ...tdStyle, textAlign: 'center', fontWeight: 'bold', fontFamily: 'monospace' }}>
                                {originalPrice.toLocaleString()} {order.currency}
                            </td>
                            <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right', fontWeight: 'bold', fontFamily: 'monospace', color: '#1e3a8a' }}>
                                {productPriceMRU.toLocaleString()}
                            </td>
                        </tr>
                        <tr>
                            <td style={tdStyle}>
                                <div style={{ fontWeight: '900', fontSize: '15px' }}>{txt.commission}</div>
                                <div style={{ fontSize: '11px', color: '#64748b' }}>{txt.fees}</div>
                            </td>
                            <td style={{ ...tdStyle, textAlign: 'center', color: '#94a3b8' }}>-</td>
                            <td style={{ ...tdStyle, textAlign: 'center', color: '#94a3b8' }}>-</td>
                            <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right', fontWeight: 'bold', fontFamily: 'monospace' }}>
                                {commission.toLocaleString()}
                            </td>
                        </tr>
                        {!isShippingPending && (
                            <tr>
                                <td style={tdStyle}>
                                    <div style={{ fontWeight: '900', fontSize: '15px' }}>{txt.shipping}</div>
                                    <div style={{ fontSize: '11px', color: '#64748b' }}>{order.weight} KG</div>
                                </td>
                                <td style={{ ...tdStyle, textAlign: 'center', color: '#94a3b8' }}>-</td>
                                <td style={{ ...tdStyle, textAlign: 'center', color: '#94a3b8' }}>-</td>
                                <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right', fontWeight: 'bold', fontFamily: 'monospace' }}>
                                    {shipping.toLocaleString()}
                                </td>
                            </tr>
                        )}
                        {!isShippingPending && delivery > 0 && (
                            <tr>
                                <td style={tdStyle}>
                                    <div style={{ fontWeight: '900', fontSize: '15px' }}>{txt.delivery}</div>
                                </td>
                                <td style={{ ...tdStyle, textAlign: 'center', color: '#94a3b8' }}>-</td>
                                <td style={{ ...tdStyle, textAlign: 'center', color: '#94a3b8' }}>-</td>
                                <td style={{ ...tdStyle, textAlign: isRtl ? 'left' : 'right', fontWeight: 'bold', fontFamily: 'monospace' }}>
                                    {delivery.toLocaleString()}
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>

                {/* Footer Notes */}
                {isShippingPending && (
                    <div style={{ padding: '20px', backgroundColor: '#fffbeb', borderRadius: '12px', border: '1px solid #fef3c7', display: 'flex', gap: '15px', alignItems: 'flex-start' }}>
                        <div style={{ color: '#d97706', marginTop: '2px' }}><AlertCircle size={20}/></div>
                        <p style={{ margin: 0, fontSize: '13px', color: '#92400e', fontWeight: 'bold', lineHeight: '1.6' }}>{txt.shippingNote}</p>
                    </div>
                )}
            </div>

            {/* Calculations Footer */}
            <div style={{ padding: '40px', backgroundColor: '#f8fafc', borderTop: '1px solid #e2e8f0', marginTop: 'auto' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
                    <div>
                        <h4 style={{ fontSize: '11px', fontWeight: 'bold', color: '#64748b', textTransform: 'uppercase', marginBottom: '10px' }}>{txt.method}</h4>
                        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '10px 20px', backgroundColor: 'white', border: '1px solid #e2e8f0', borderRadius: '12px', fontWeight: 'bold', fontSize: '14px' }}>
                            <Wallet size={16} className="text-primary"/>
                            {order.paymentMethod || 'Cash'}
                        </div>
                    </div>
                    <div style={{ minWidth: '280px' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px', fontSize: '14px', fontWeight: 'bold' }}>
                            <span style={{ color: '#64748b' }}>{txt.total}</span>
                            <span style={{ fontFamily: 'monospace', fontSize: '18px' }}>{totalDue.toLocaleString()} {txt.currency}</span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '16px', fontSize: '14px', fontWeight: 'bold', color: '#059669' }}>
                            <span>{txt.paid}</span>
                            <span style={{ fontFamily: 'monospace', fontSize: '18px' }}>{paid.toLocaleString()}</span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 25px', backgroundColor: remaining > 0 ? '#0f172a' : '#059669', borderRadius: '16px', color: 'white' }}>
                            <span style={{ fontWeight: 'bold', fontSize: '13px', textTransform: 'uppercase' }}>{txt.remaining}</span>
                            <span style={{ fontSize: '26px', fontWeight: '900', fontFamily: 'monospace' }}>{remaining.toLocaleString()} <span style={{ fontSize: '12px', opacity: 0.8 }}>{txt.currency}</span></span>
                        </div>
                    </div>
                </div>

                <div style={{ marginTop: '50px', textAlign: 'center' }}>
                    <p style={{ fontSize: '12px', color: '#94a3b8', fontWeight: 'bold', textTransform: 'uppercase', marginBottom: '6px' }}>{txt.termsHeader}</p>
                    <p style={{ fontSize: '13px', color: '#64748b', margin: 0 }}>{companyInfo.invoiceTerms || txt.terms}</p>
                </div>
            </div>
        </div>
    );
};

// --- Main Modal Component ---
const InvoiceModal: React.FC<InvoiceModalProps> = ({ isOpen, onClose, order, client, store, companyInfo, onSuccess }) => {
    const hiddenInvoiceRef = useRef<HTMLDivElement>(null); 
    const [genStatus, setGenStatus] = useState<GenerationStatus>('idle');
    const [preparedFile, setPreparedFile] = useState<File | null>(null);
    const [selectedLang, setSelectedLang] = useState<LangCode | null>(null);
    const [previewScale, setPreviewScale] = useState(1);

    useEffect(() => {
        if (isOpen) {
            setSelectedLang(null);
            setGenStatus('idle');
            setPreparedFile(null);
            const updateScale = () => {
                const width = window.innerWidth - 32;
                setPreviewScale(Math.min(width / A4_WIDTH_PX, 1));
            };
            updateScale();
            window.addEventListener('resize', updateScale);
            return () => window.removeEventListener('resize', updateScale);
        }
    }, [isOpen]);

    if (!isOpen) return null;

    const performAction = async (action: InvoiceAction) => {
        if (!hiddenInvoiceRef.current) return;
        setGenStatus('generating');

        try {
            // CRITICAL: Ensure layout is ready
            await document.fonts.ready;
            await new Promise(resolve => setTimeout(resolve, 800)); 

            const captureEl = hiddenInvoiceRef.current;
            const originalStyle = captureEl.style.cssText;
            
            // Show off-screen
            captureEl.style.position = 'fixed';
            captureEl.style.top = '0';
            captureEl.style.left = '0';
            captureEl.style.visibility = 'visible';
            captureEl.style.display = 'block';
            captureEl.style.zIndex = '9999';

            const canvas = await html2canvas(captureEl, {
                scale: 2, 
                useCORS: true,
                allowTaint: true,
                backgroundColor: '#ffffff',
                logging: false,
                width: A4_WIDTH_PX,
                height: captureEl.scrollHeight
            });

            captureEl.style.cssText = originalStyle;

            if (action === 'print') {
                const imgData = canvas.toDataURL('image/png');
                const printWindow = window.open('', '_blank');
                if (printWindow) {
                    printWindow.document.write(`
                        <html>
                            <head><title>Invoice #${order.localOrderId}</title></head>
                            <body style="margin:0; background:#eee; display:flex; justify-content:center;">
                                <img src="${imgData}" style="width:100%; max-width:210mm; background:white;" onload="window.print();"/>
                            </body>
                        </html>
                    `);
                    printWindow.document.close();
                    if (onSuccess) onSuccess(); 
                    setGenStatus('idle');
                }
            } else {
                const imgData = canvas.toDataURL('image/jpeg', 0.95);
                const pdfWidth = 210; // mm
                const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
                
                const pdf = new jsPDF({
                    orientation: pdfHeight > pdfWidth ? 'p' : 'l',
                    unit: 'mm',
                    format: [pdfWidth, pdfHeight]
                });

                pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight);
                const pdfBlob = pdf.output('blob');
                const fileName = `Invoice-${order.localOrderId}.pdf`;
                const file = new File([pdfBlob], fileName, { type: 'application/pdf' });

                if (action === 'share') {
                    setPreparedFile(file);
                    setGenStatus('ready_to_share');
                } else if (action === 'download') {
                    pdf.save(fileName);
                    if (onSuccess) onSuccess(); 
                    setGenStatus('idle');
                }
            }

        } catch (error) {
            console.error('Invoice generation error:', error);
            setGenStatus('error');
            alert('حدث خطأ أثناء معالجة الفاتورة.');
        }
    };

    const handleActualShare = async () => {
        if (!preparedFile) return;
        try {
            if (navigator.share && navigator.canShare && navigator.canShare({ files: [preparedFile] })) {
                await navigator.share({
                    files: [preparedFile],
                    title: `Invoice ${order.localOrderId}`,
                    text: `فاتورة الطلب #${order.localOrderId} - ${companyInfo.name}`,
                });
                if (onSuccess) onSuccess();
                setGenStatus('idle');
                setPreparedFile(null);
            } else {
                const link = document.createElement('a');
                link.href = URL.createObjectURL(preparedFile);
                link.download = preparedFile.name;
                link.click();
                setGenStatus('idle');
            }
        } catch (e) {
            if ((e as Error).name !== 'AbortError') {
                setGenStatus('error');
            }
        }
    };

    // Stage 1: Language Picker
    if (!selectedLang) {
        return (
            <div className="fixed inset-0 bg-slate-900/95 z-[120] flex items-center justify-center p-4 backdrop-blur-md" onClick={onClose}>
                <div className="bg-white dark:bg-slate-800 rounded-3xl shadow-2xl p-8 w-full max-w-sm text-center animate-in zoom-in-95 duration-200" onClick={e => e.stopPropagation()}>
                    <div className="w-20 h-20 bg-indigo-50 dark:bg-indigo-900/30 rounded-full flex items-center justify-center mx-auto mb-6 text-indigo-600 dark:text-indigo-400">
                        <Globe size={40}/>
                    </div>
                    <h3 className="text-2xl font-black text-slate-800 dark:text-white mb-2">لغة الفاتورة</h3>
                    <p className="text-slate-500 dark:text-slate-400 mb-8 text-sm">اختر لغة العرض والمشاركة المفضلة للفاتورة</p>
                    
                    <div className="space-y-3">
                        {(['ar', 'en', 'fr'] as LangCode[]).map(lang => (
                            <button key={lang} onClick={() => setSelectedLang(lang)} className="w-full p-4 rounded-2xl border-2 border-slate-100 dark:border-slate-700 hover:border-indigo-500 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 flex items-center justify-between group transition-all">
                                <span className="font-bold text-slate-700 dark:text-slate-200 text-lg">
                                    {lang === 'ar' ? 'العربية' : lang === 'en' ? 'English' : 'Français'}
                                </span>
                                <span className="text-2xl grayscale group-hover:grayscale-0 transition-all">
                                    {lang === 'ar' ? '🇦🇪' : lang === 'en' ? '🇺🇸' : '🇫🇷'}
                                </span>
                            </button>
                        ))}
                    </div>
                    <button onClick={onClose} className="mt-8 text-slate-400 hover:text-slate-600 font-bold transition-colors">إلغاء</button>
                </div>
            </div>
        );
    }

    // Stage 2: Preview & Action
    return (
        <>
            {genStatus !== 'idle' && (
                <div className="fixed inset-0 z-[10000] bg-white/95 dark:bg-slate-900/95 backdrop-blur-md flex flex-col items-center justify-center p-6 text-center animate-in fade-in duration-300">
                    <div className="relative w-32 h-32 mb-8">
                        {genStatus === 'generating' ? (
                            <>
                                <div className="absolute inset-0 border-4 border-indigo-500/20 rounded-full"></div>
                                <div className="absolute inset-0 border-4 border-indigo-500 rounded-full border-t-transparent animate-spin"></div>
                                <div className="absolute inset-0 flex items-center justify-center text-indigo-500">
                                    <FileText size={40}/>
                                </div>
                            </>
                        ) : genStatus === 'ready_to_share' ? (
                            <div className="bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 w-full h-full rounded-full flex items-center justify-center shadow-lg animate-in zoom-in duration-500">
                                <Check size={48} strokeWidth={3}/>
                            </div>
                        ) : (
                            <div className="bg-red-100 dark:bg-red-900/30 text-red-600 w-full h-full rounded-full flex items-center justify-center shadow-lg">
                                <AlertCircle size={48}/>
                            </div>
                        )}
                    </div>
                    
                    <h3 className="text-2xl font-black text-slate-800 dark:text-white mb-3">
                        {genStatus === 'generating' ? 'جاري تجهيز الفاتورة' : genStatus === 'ready_to_share' ? 'الفاتورة جاهزة للإرسال' : 'حدث خطأ ما'}
                    </h3>
                    <p className="text-slate-500 dark:text-slate-400 max-w-xs mx-auto text-sm mb-10 leading-relaxed">
                        {genStatus === 'generating' 
                            ? 'نقوم الآن بتحويل الفاتورة إلى ملف PDF عالي الجودة متوافق مع كافة الأجهزة...' 
                            : genStatus === 'ready_to_share' 
                            ? 'تم إنشاء الملف بنجاح. اضغط على الزر أدناه لمشاركته عبر واتساب أو أي تطبيق آخر.'
                            : 'لم نتمكن من معالجة الفاتورة حالياً، يرجى المحاولة لاحقاً.'}
                    </p>

                    {genStatus === 'ready_to_share' && (
                        <div className="flex flex-col gap-3 w-full max-w-xs">
                            <button 
                                onClick={handleActualShare}
                                className="w-full py-4 bg-indigo-600 hover:bg-indigo-700 text-white rounded-2xl font-black shadow-xl shadow-indigo-500/30 flex items-center justify-center gap-3 transition-all active:scale-95"
                            >
                                <Share2 size={24}/> مشاركة الآن
                            </button>
                            <button 
                                onClick={() => setGenStatus('idle')}
                                className="w-full py-4 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 rounded-2xl font-bold transition-all"
                            >
                                رجوع للمعاينة
                            </button>
                        </div>
                    )}

                    {(genStatus === 'generating' || genStatus === 'error') && (
                        <button 
                            onClick={() => setGenStatus('idle')}
                            className="py-3 px-8 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 rounded-xl font-bold transition-all"
                        >
                            إلغاء
                        </button>
                    )}
                </div>
            )}

            <div className="fixed inset-0 bg-slate-900 z-[120] flex flex-col backdrop-blur-sm overflow-hidden animate-in fade-in">
                {/* Fixed Control Bar */}
                <div className="absolute top-0 left-0 w-full p-4 flex justify-between items-center z-[150] pointer-events-none">
                    <button onClick={() => setSelectedLang(null)} className="p-3 bg-slate-800/80 hover:bg-slate-700 text-white rounded-full backdrop-blur-md pointer-events-auto transition-all flex items-center gap-2 px-5 shadow-lg border border-white/10 active:scale-95">
                        <ChevronLeft size={20}/> <span className="text-sm font-bold hidden sm:inline">تغيير اللغة</span>
                    </button>
                    <button onClick={onClose} className="p-3 bg-slate-800/80 hover:bg-slate-700 text-white rounded-full backdrop-blur-md pointer-events-auto transition-all shadow-lg border border-white/10 active:scale-95">
                        <X size={24}/>
                    </button>
                </div>

                {/* Scaled Preview Area */}
                <div className="flex-1 overflow-y-auto w-full custom-scrollbar flex justify-center bg-slate-900">
                    <div className="pt-24 pb-32 px-4" style={{ width: '100%', display: 'flex', justifyContent: 'center' }}>
                        <div style={{
                            width: `${A4_WIDTH_PX}px`,
                            transform: `scale(${previewScale})`,
                            transformOrigin: 'top center',
                            marginBottom: `${-(A4_HEIGHT_PX * (1 - previewScale))}px`,
                            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)'
                        }}>
                            <InvoiceTemplate order={order} client={client} store={store} companyInfo={companyInfo} lang={selectedLang} />
                        </div>
                    </div>
                </div>

                {/* Hidden Ref for Capture (Standardized Size) */}
                <div 
                    ref={hiddenInvoiceRef}
                    style={{
                        position: 'fixed',
                        top: 0,
                        left: '-9999px',
                        width: `${A4_WIDTH_PX}px`,
                        zIndex: -100, 
                        visibility: 'hidden', 
                        backgroundColor: 'white',
                        pointerEvents: 'none'
                    }}
                >
                    <InvoiceTemplate order={order} client={client} store={store} companyInfo={companyInfo} lang={selectedLang} />
                </div>

                {/* Bottom Action Dock */}
                <div className="absolute bottom-8 left-1/2 -translate-x-1/2 bg-white/10 backdrop-blur-xl border border-white/20 p-2 rounded-3xl flex gap-3 shadow-2xl z-[150] animate-in slide-in-from-bottom-10 duration-500">
                    <button 
                        onClick={() => performAction('share')}
                        disabled={genStatus !== 'idle'}
                        className="flex flex-col items-center justify-center w-16 h-16 rounded-2xl bg-white hover:bg-slate-50 text-indigo-600 transition-all active:scale-90 group"
                    >
                        <Share2 size={24} className="group-hover:-translate-y-1 transition-transform"/>
                        <span className="text-[10px] font-black mt-1">مشاركة</span>
                    </button>

                    <button 
                        onClick={() => performAction('print')}
                        disabled={genStatus !== 'idle'}
                        className="flex flex-col items-center justify-center w-16 h-16 rounded-2xl bg-white hover:bg-slate-50 text-indigo-600 transition-all active:scale-90 group"
                    >
                        <Printer size={24} className="group-hover:-translate-y-1 transition-transform"/>
                        <span className="text-[10px] font-black mt-1">طباعة</span>
                    </button>

                    <button 
                        onClick={() => performAction('download')}
                        disabled={genStatus !== 'idle'}
                        className="flex flex-col items-center justify-center w-16 h-16 rounded-2xl bg-indigo-600 text-white hover:bg-indigo-700 transition-all active:scale-90 group shadow-lg shadow-indigo-500/30"
                    >
                        <Download size={24} className="group-hover:-translate-y-1 transition-transform"/>
                        <span className="text-[10px] font-black mt-1">حفظ</span>
                    </button>
                </div>
            </div>
        </>
    );
};

export default InvoiceModal;
